### ISSUE TITLE
`filter_record_transformer` mixes up contexts under load

### ISSUE THREAD

**Issue by replay** [treasure-data/td-agent#85]
I have multiple sources defined which are collecting events. All of those events are going through one single `filter` tag that uses the `filter_record_transformer` to add the `tag` into the payload data. This works in most of the cases, but from time to time (like in 1 of many thousand) it happens that the tag which is added to the payload data belongs to another event, meaning the `record_transformer` must somehow mix up the contexts between the events.

After I saw this problem happen I created a minimal config to reproduce it:

    <source>
      type tcp
      bind localhost
      port 2001
      format json
      tag in1
    </source>

    <source>
      type tcp
      bind localhost
      port 2002
      format json
      tag in2
    </source>

    <filter **>
      type record_transformer
      enable_ruby true
      <record>
        tag ${tag}
      </record>
    </filter>

    <match in1>
      type file
      path /tmp/out1
    </match>

    <match in2>
      type file
      path /tmp/out2
    </match>

Then I run these two commands at the same time in two terminals to generate traffic:

    for i in {1..10000}; do echo '{}' | nc  ::1 2001; done
    for i in {1..10000}; do echo '{}' | nc  ::1 2002; done

This generates two files in `/tmp` as defined in the `match` tags.

    root@ubuntu.test dev ~ # grep in1 /tmp/out2.20151117.b524bd21442bed282 
    2015-11-17T21:13:48+07:00	in2	{"tag":"in1"}
    root@ubuntu.test dev ~ # grep in2 /tmp/out1.20151117.b524bd1ea7c3eafcd 
    root@ubuntu.test dev ~ # 

This one line that's found in the file `/tmp/out2.20151117.b524bd21442bed282` illustrates the problem, my grep should not find anything.

**Comment by repeatedly** [comment]
Sorry I missed this PR because we have already moved to omnibus-td-agent: https://github.com/treasure-data/td-agent#note

BTW, If you have fluentd related question or issue, use fluentd ML or repository instead of td-agent repositories.

Currenlty, `record_transformer` has placeholder status for expanding values.
Maybe, this causes a race condition.
In your case, using https://github.com/repeatedly/fluent-plugin-record-modifier instead of record_transformer resolve your problem.
We will relax this record_transformer limitation in the future.
